sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
env:
  global:
  - secure: MFozIsgJTNfpsN7jBEbCoaKtd76zLVlYvFTHViRmAqfOeu/IQgybq7T/fVK1Oufz6IKlXC8QaDldJsWyPRKOQ2MSOElZgxXcAmkWPXmmsdit7xyrwXDwefILP+Ucc7KnwzP2JCAswMTAoYU3SnLbhP45WfhvoIWVCuyMHswFwK69HmyONYEC0jOAjYdp/5vpjaU6qjtrZYpIqgVxNfovCHcrMGCC2vLIW4M+pg3vXbYpBVCr4pFkfRFQ+H+PxhbH6dq7whd5mTDSmsDa5psPUOhxgcwKZ9Xt0t303vR15C0aPCp5vebXSKuyxG1ZhY04ogB2BXcqu6F35zbLWcmprLOXXVsUvFXCeCY89FruGfAD/XsXGQGWtAauCAtYOE2qaJXsIsWBJpjsK28jxySCOPjAnVHwoUoDAm5nSip8+e+goMT/16QB6cpVMdZFltGmIsyMDY7G4Nvri91wAgR12U0sHlVPK3vU8+CIFqhRZI40VnXYkuZSUWfBMZEhtmZQhh58sD9M1JuAmEuAEOq6XiOY+jK9Q+1VMT+z3tlUkK21o+fpBFnO/O6bs5gcgJkCuxf8HezEDIjBdG45+tS9qjmmRvy+jr2DKPMT7zIHNYWUUy3tiXbb2A2yCMvuzjhiNFGCc6YBHkjVroel76t8H/ooDY+vzTc8cPXqGs4DDXY=
  - secure: R6kG7o15OS3BSqMxt2VniiDa687XKzteP481OJxa/vZJRyCuRSRqUSQUN0rZw2rBRrcGvn3C6BBYahE4+8Gi6eyjSn7eUWuU8NY27wfCzIQ32BBk4zZKha4ah8rfYv5q3vgmUz5I9/B/G1xkcWixu1Qh6gK/e/JXWCjx+VYc5IkD9fTtoQ9QmhQtCycz/7AF8A3Fx7vLpYBkn9EfKSO0TRlPa3co8ZC3u33R7dnWtH6aXDlS5K0OePaUn0jw4/m5Eo9ogbNTZRsWDE9QVTwC2lkBASuzO28ukipn03/hopEpNeE4CX7h7nuJ36YcNBQPcNex9KKJ9CaHcda8QhMP8gnyUt3bdaADjzuXiSq1yAzd2IfFsqAqNwadHG2lBX8CZRdQ4AtGR71dPaaPJVdCDbjX94iyBjYpBAJ6jfMAC31XXUaHYrfjyvL9WjWHYVCTtofvWgILfgZPZJ1KHSpKRS00sK5TOChnxGd6CzCX2cbcMSigNu+Y3igrKnCFIlDPc4cGcYspIUhLPqT7HmMU/6CpD3DNYjkXN3wctBf+UkA6Nf2kX23xWPLUjvWrYkuABf9h2V3fjEQQcWrM1DzsKnUknLvkIcy4gIYT6pfVjPAGm5QEdRZJ/PrFZUuIhwqoHaviIxfYuOnWinusA1DXPUirbBAHef5zlyo/VzfNcSM=
